os: 
  - linux
  
language: shell

addons:
  apt:
    packages:
      - libxml2-utils
      - ant
      
branches:
  only:
  - master
  
env:
  global:
  - ENCRYPTION_LABEL: f641f006de37
  
script:
- bash check-saml-metadata/check_saml_metadata.sh metadata/

after_success:
- bash CI-assets/deploy.sh

notifications:
  email:
    on_success: change
    on_failure: always
